POST http://localhost:3000/signup
Content-Type: application/json

{
    "username": "haki",
    "email": "hakixer@gmail.com",
    "password": "hakisolos"
}

###
POST http://localhost:3000/login
Content-Type: application/json

{
    "email": "hakixer@gmail.com",
    "password": "hakisolos"
}

###
GET http://localhost:3000/users



